# Generated by Django 4.2.9 on 2024-02-18 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("makeup_api", "0002_alter_product_ingredients"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="type",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
