# Generated by Django 4.2.9 on 2024-02-19 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("makeup_api", "0003_product_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="product_images/"),
        ),
    ]
