# Generated by Django 4.2.9 on 2024-04-01 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("makeup_api", "0004_product_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product", old_name="ingredients", new_name="product_colors",
        ),
        migrations.RemoveField(model_name="product", name="image",),
        migrations.RemoveField(model_name="product", name="shade_name",),
        migrations.RemoveField(model_name="product", name="type",),
        migrations.RemoveField(model_name="product", name="user_reviews",),
        migrations.AddField(
            model_name="product",
            name="alcohol_free",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="api_featured_image",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="canadian",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="certclean",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="chemical_free",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="cruelty_free",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="currency",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="dairy_free",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="ecocert",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="ewg_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="fair_trade",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="gluten_free",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="hypoallergenic",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="natural",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="no_talc",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="non_gmo",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="oil_free",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="organic",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="peanut_free_product",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="price_sign",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="product_api_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="product_id",
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="product",
            name="product_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="product_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="purpicks",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="silicone_free",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="sugar_free",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="usda_organic",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="vegan",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="water_free",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="website_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="brand",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
