# Generated by Django 4.2.9 on 2024-02-14 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("shade_name", models.CharField(max_length=100)),
                ("brand", models.CharField(max_length=100)),
                ("ingredients", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=6)),
                ("user_reviews", models.TextField()),
            ],
        ),
    ]
