# Generated by Django 4.2.9 on 2024-02-14 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("makeup_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product", name="ingredients", field=models.JSONField(),
        ),
    ]
