# Generated by Django 4.2.9 on 2024-04-02 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("makeup_api", "0005_rename_ingredients_product_product_colors_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_colors",
            field=models.JSONField(default=list),
        ),
    ]
