# Generated by Django 4.2.9 on 2024-04-05 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("makeup_api", "0006_alter_product_product_colors"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="ingredients",
            field=models.TextField(blank=True, null=True),
        ),
    ]
